GradExam/Models/Concentration.cs
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
// 
// Solution/Project: GradExam/GradExam
// File Name: Concentration.cs 
// Description: Functions as the main model for Concentration. Handles fields for a specific Concentration object
// 
// Course: CSCI 3250-001 - Software Engineering I  
// Author: Levi Shelton, SHELTONL@etsu.edu 
// Created: December, October 05, 2018 
// Copyright: Scrum Bags, 2018
// 
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GradExam.Models
{
    public class Concentration
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

    }
}

GradExam/Controllers/ConcentrationController.cs
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
// 
// Solution/Project: GradExam/GradExam
// File Name: HomeController.cs 
// Description: Functions as the main controller for the concentration page of the program. Displays and handles 
//              controlling for an index page, editing, adding or deleting concentration via regular functions or page
//              redirections. 
// 
// Course: CSCI 3250-001 - Software Engineering I  
// Author: Levi Shelton, SHELTONL@etsu.edu 
// Created: December, October 05, 2018 
// Copyright: Scrum Bags, 2018
// 
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GradExam.Models;
using GradExam.Services;
using GradExam.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GradExam.Controllers
{
	/// <summary>
    /// Controller for creating/editing/deleting a Course
    /// </summary>
    [Authorize(Roles ="Admin,Director")]
    public class ConcentrationController : Controller
    {
        private IGradeExamRepository _context;
		/// <summary>
		/// Parameterized constructor for creating a context to IGradeExamRepository
		/// </summary>
		/// <param name="context">The view model for resetting a password</param>
		/// <returns></returns>
        public ConcentrationController(IGradeExamRepository context)
        {
            _context = context;
        }
		/// <summary>
		/// IAction method for returning an index view
		/// </summary>
        public IActionResult Index()
        {
            var concentrations = _context.ReadAllConcentrations();
            return View(concentrations);
        }
		/// <summary>
		/// IAction method for handling returning an edit view
		/// </summary>
		/// <param name="id">Id for a concentration</param>
		/// <param name="read"></param>
		/// <returns>Handles read only instructions</returns>
        public IActionResult Edit(int id, bool read = false)
        {
            var concentration = _context.ReadConcentration(id);

            var vm = new EditConcentrationViewModel
            {
                ReadOnly = read,
                Id = concentration.Id,
                Title = concentration.Name
            };

            return View(vm);
        }
		/// <summary>
		/// IAction method for posting the results of an Edit, handles validation
		/// </summary>
		/// <param name="id">Id for a concentration</param>
		/// <param name="vm">view model to edit</param>
		/// <returns></returns>
        [HttpPost]
        public IActionResult Edit(int id, EditConcentrationViewModel vm)
        {
            //Make sure the model state is valid
            if (!ModelState.IsValid)
            {
                return View("Edit", vm);
            }

            Concentration concentration;

            // If we are adding a concentration
            if (id == -1)
            {
                concentration = new Concentration
                {
                    Name = vm.Title
                };

                _context.UpdateConcentration(-1, concentration);
            }
            else //Editing a concentration
            {
                concentration = _context.ReadConcentration(id);

                concentration.Name = vm.Title;

                _context.UpdateConcentration(id, concentration);
            }

            return RedirectToAction("Index");
        }
		/// <summary>
		/// IAction method for returning an addition view
		/// </summary>
		/// <returns></returns>
        public IActionResult Add()
        {
            //Create view model with -1 as id to signify we are adding a concentration
            var vm = new EditConcentrationViewModel();
            vm.Id = -1;

            return View("Edit",vm);
        }
		/// <summary>
		/// IAction method for returning a delete view
		/// </summary>
		/// <param name="id">Id for a concentration</param>
		/// <returns></returns>
        public IActionResult Delete(int id)
        {
            var con = _context.ReadConcentration(id);
            if (con == null)
            {
                return RedirectToAction("Index");
            }
            return View(con);
        }
		/// <summary>
		/// IAction method for handling a deletion confirmed.
		/// </summary>
		/// <param name="id">Id for a concentration</param>
		/// <returns></returns>
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _context.DeleteConcentration(id);
            return RedirectToAction("Index");
        }
    }
}

GradExam/Views/Concentration/Delete.cshtml
<!-- View for deleting a concentration -->
@model GradExam.Models.Concentration

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Concentration</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GradExam/Views/Concentration/Edit.cshtml
<!-- View for editing in a concentration -->
@model GradExam.ViewModels.EditConcentrationViewModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm("Edit", "Concentration"))
{
    <div class="col-sm-4">

        @Html.ValidationSummary()
        <div class="form-group">
            <!--  Needs to be read only  -->
            @Html.LabelFor(model => model.Id)
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly"} })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title)
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        <button type="submit" class="btn btn-primary" id="submit">Submit</button>
    
    </div>
}

<script>
    document.getElementById("Title").readOnly = @(Model.ReadOnly ? "true" : "false");
    $("#submit").css("visibility", "@(Model.ReadOnly ? "hidden" : "")");

</script>

GradExam/Views/Concentration/Index.cshtml
<!-- View for displaying the index of a concentration -->
@model IEnumerable<GradExam.Models.Concentration>
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Add">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Concentration", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Edit", "Concentration", new { id = item.Id, read = true }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id  })
                </td>
            </tr>
        }
    </tbody>
</table>