GradExam/Models/LearnOutcome.cs
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
// 
// Solution/Project: GradExam/GradExam
// File Name: LearnOutcome.cs 
// Description: Functions as the main model for LearnOutcome. Handles fields for a specific LearnOutcome object
// 
// Course: CSCI 3250-001 - Software Engineering I  
// Author: Levi Shelton, SHELTONL@etsu.edu 
// Created: December, October 05, 2018 
// Copyright: Scrum Bags, 2018
// 
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GradExam.Models
{
    public class LearnOutcome
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Learning Outcome")]
        public string LearningOutcome { get; set; }
        
        [Display(Name = "Question")]
        public List<QuesAnswer> QuestionAnswer { get; set; }


    }
}

GradExam/Controllers/LearnOutcomeController.cs
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
// 
// Solution/Project: GradExam/GradExam
// File Name: LearnOutcomeController.cs 
// Description: Functions as the main controller for the learning outcome page of the program. Displays and handles 
//              controlling for an index page, details for learning outcomes, adding/deleting 
//              learning outcomes, adding/deleting, updating a concentration via regular functions or page
//              redirections. 
// 
// Course: CSCI 3250-001 - Software Engineering I  
// Author: Levi Shelton, SHELTONL@etsu.edu 
// Created: December, October 05, 2018 
// Copyright: Scrum Bags, 2018
// 
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GradExam.Services;
using GradExam.ViewModels;
using GradExam.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace GradExam.Controllers
{	/// <summary>
		/// Controller for a learning outcome functionality
		/// </summary>
    [Authorize(Roles = "Admin,Director")]
    public class LearnOutcomeController : Controller
    {
        private IGradeExamRepository context;
		/// <summary>
		/// Constructor for creating IGradeExamRepository connectivity
		/// </summary>
		/// <param name="context">connection to IGradeExamRepository</param>
		/// <returns></returns>
        public LearnOutcomeController(IGradeExamRepository context)
        {
            this.context = context;
        }
		/// <summary>
		/// IAction method for returning a learningOutcome index view
		/// </summary>
		/// <returns></returns>
        public IActionResult Index()
        {
            var model = context.ReadAllOutcomes();
            return View(model);
        }
		/// <summary>
		/// IAction method for returning a deletion view
		/// </summary>
		/// <param name="id">Id for a learningOutcome</param>
		/// <returns></returns>
        public IActionResult Delete(int id)
        {
            LearnOutcome Lout = context.ReadOutcome(id);
            if (Lout == null)
            {
                return RedirectToAction("Index");
            }
            return View(Lout);
        }
		/// <summary>
		/// IAction method for posting the results of a deletion
		/// </summary>
		/// <param name="id">Id for a learningOutcome</param>
		/// <returns></returns>
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            context.DeleteOutcome(id);
            return RedirectToAction("Index");
        }
		/// <summary>
		/// IAction method for returning details of a learningOutcome
		/// </summary>
		/// <param name="id">Id for a learningOutcome</param>
		/// <returns></returns>
        public IActionResult Details(int id)
        {
            LearnOutcome learn = context.ReadOutcome(id);
            if (learn == null)
            {
                return RedirectToAction("Index");
            }
            return View(learn);
        }
		/// <summary>
		/// IAction method for returning an update of a learningOutcome
		/// </summary>
		/// <param name="id">Id for a learningOutcome</param>
		/// <returns></returns>
        public IActionResult Update(int id)
        {
            // Get the list of Questions and Answers
            var listQA = context.ReadAllQuesAnswers().ToList();
            ViewBag.QAs = listQA;

            var model = context.ReadOutcome(id);

            var vm = new EditLearnOutcomeViewModel()
            {
                LearningOutcome = model,
                //QuestionId = model.QuestionAnswer.Id
            };

            return View(vm);
        }
		/// <summary>
		/// IAction method for posting the results of updating a learningOutcome
		/// </summary>
		/// <param name="vm">viewmodel for the update</param>
		/// <returns></returns>
        [HttpPost]
        public IActionResult Update(EditLearnOutcomeViewModel vm)
        {
            // Validate the model
            if (!ModelState.IsValid)
            {
                // Get the view model and return it
                return View("Update", vm);
            }

            //Add the question and answer to the learning outcome
            vm.LearningOutcome.QuestionAnswer.Add(context.ReadQuesAnswer(vm.QuestionId));
            context.UpdateOutcome(vm.LearningOutcome.Id, vm.LearningOutcome);
            return RedirectToAction("Index");
        }
		/// <summary>
		/// IAction method for returning an add view with details
		/// </summary>
		/// <returns></returns>
        [HttpGet]
        public IActionResult Add()
        {
            // Get the list of Questions and Answers
            var listQA = context.ReadAllQuesAnswers().ToList();
            ViewBag.QAs = listQA;

            var vm = new AddLearnOutcomeViewModel();
            return View(vm);
        }
		/// <summary>
		/// IAction method for posting the result of adding a learning outcome to a viewmodel
		/// </summary>
		/// <param name="vm">viewmodel for addition</param>
		/// <returns></returns>
        [HttpPost]
        public IActionResult Add(AddLearnOutcomeViewModel vm)
        {

            if (!ModelState.IsValid)
            {
                return View("Add", vm);
            }

            if (!ModelState.IsValid)
            {
                return View("Add", vm);
            }

            LearnOutcome Lo = new LearnOutcome
            {
                LearningOutcome = vm.LearningOutcome,
                QuestionAnswer = new List<QuesAnswer>()
            };

            Lo.QuestionAnswer.Add(context.ReadQuesAnswer(vm.QuestionId));

            context.CreateLearningOutcome(Lo);
            return RedirectToAction("Index");
        }

    }
}

GradExam/Views/LearnOutcome/Add.cshtml
@model GradExam.ViewModels.AddLearnOutcomeViewModel

@using (Html.BeginForm("Add","LearnOutcome"))
{
<div class="col-sm-4">
    <div class="form-group">
        @Html.LabelFor(model => model.LearningOutcome, new { style = "width: 160px;" })
        @Html.TextAreaFor(model => model.LearningOutcome, new { rows = "10", cols = "120", @maxlength = "900", style = "width: 900px;", htmlAttributes = new { @class = "form-control" } })
    </div>
    @*<div class="form-group">
        @Html.Label("Question and Answer")
        @Html.DropDownListFor(model => model.QuestionId, new SelectList(@ViewBag.QAs, "Id", "Question"), "--- Q&A ---", new { @class = "form-control" })
    </div>*@
    <button type="submit" class="btn btn-primary">Create Learning Outcome</button>
</div>
}

GradExam/Views/LearnOutcome/Delete.cshtml
@model GradExam.Models.LearnOutcome

@{
    ViewData["Title"] = $"Delete LearnOutcome: {Model.Id}";
}

<h2>@ViewData["Title"]</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LearnOutcome</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LearningOutcome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LearningOutcome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.QuestionAnswer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuestionAnswer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index" asp-controller="Home">Back to List</a>
    </form>
</div>

GradExam/Views/LearnOutcome/Details.cshtml
@model GradExam.Models.LearnOutcome

@{
    ViewData["Title"] = "View Learning Outcome";
}

<h2>View Learning Outcome</h2>

<div>
    <h4>Learning Outcome</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LearningOutcome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LearningOutcome)
        </dd>
    </dl>
    <table class="table">
        <thead>
            <tr>
                <th>Question</th>
                <th>Answer</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.QuestionAnswer)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => item.Question)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Answer)
                    </td>
                </tr>
            }
        </tbody>
    </table>

    </div>
<div>
    <a asp-action="Update" asp-controller="LearnOutcome" asp-route-id="@Model.Id">Edit</a>
    <a asp-action="Index">Back to List</a>
</div>

GradExam/Views/LearnOutcome/Index.cshtml
@model IEnumerable<GradExam.Models.LearnOutcome>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Add">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LearningOutcome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LearningOutcome)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Update", "LearnOutcome", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

GradExam/Views/LearnOutcome/Update.cshtml
@model GradExam.ViewModels.EditLearnOutcomeViewModel

@{
    ViewData["Title"] = "Update";
}

<h2>Update</h2>

<h4>Learning Outcome</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.LabelFor(model => model.LearningOutcome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.EditorFor(model => model.LearningOutcome, new { htmlAttributes = new { @class = "form-control" } })
                <span asp-validation-for="LearningOutcome" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                @Html.Label("Question and Answer")
                @Html.DropDownListFor(model => model.QuestionId, new SelectList(@ViewBag.QAs, "Id", "Question"), "--- Q&A ---", new { @class = "form-control" })
                <span asp-validation-for="QuestionId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>